-- Section Control: lets an admin edit name/subtitle/description/detail-rows
-- for every Training Hub card, reorder the cards, and flip Faith & Favor
-- Mobility / VL Body Lab / a one-off Special Event slot from hidden or
-- "in development" to live by picking a date, all from the Admin Console,
-- no code changes, no redeploy.
--
-- Reference only: this table was created live via the Supabase Table Editor
-- GUI (not by running this script), because the SQL Editor was unreliable in
-- that session. This file documents the resulting schema so it can be
-- reproduced or reviewed without opening the dashboard. It replaces the
-- earlier program_launches table (database/supabase-program-launches.sql),
-- which is left in place unused rather than dropped.

create table if not exists public.training_programs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    program_key text not null unique,
    name text not null,
    subtitle text,
    description text not null default '',
    details jsonb not null default '[]',
    note text,
    status text not null default 'live',
    launch_at timestamptz,
    expires_at timestamptz,
    sort_order integer not null default 0
);

alter table public.training_programs enable row level security;

drop policy if exists "Public can view non-hidden training programs" on public.training_programs;
create policy "Public can view non-hidden training programs"
on public.training_programs for select to public
using (status <> 'hidden');

drop policy if exists "Admins manage training programs" on public.training_programs;
create policy "Admins manage training programs"
on public.training_programs for all to authenticated
using ((select public.is_echelon_admin()))
with check ((select public.is_echelon_admin()));

-- Seed content migrated verbatim from the previously hardcoded index.html
-- training cards. status:'live' = always shown, no admin toggle exposed;
-- status:'in_development' = Faith & Favor / VL Body Lab before launch;
-- status:'hidden' = the unused special-event slot (omitted from the
-- carousel entirely until an admin publishes it).
insert into public.training_programs (program_key, name, subtitle, description, details, note, status, sort_order)
values
    ('group-fitness', 'GROUP FITNESS', 'Team Led',
     'Train with the Collective through coached group sessions built for consistency, strength, and real community.',
     '[{"label":"Access","value":"$23 drop-in · $89/month for unlimited access to all scheduled Echelon Group Fitness sessions."},{"label":"Schedule","value":"Group sessions run on a fixed published schedule, so members always know when to train and the coaching standard stays high."},{"label":"Included","value":"Complimentary for active Echelon 12-Week Transformation and 1-on-1 Hybrid Coaching clients."},{"label":"Community","value":"One session each month is free and open to the public."}]'::jsonb,
     null, 'live', 10),
    ('private-group-training', 'PRIVATE GROUP TRAINING', 'Your People · Your Purpose',
     'A customized Echelon experience for 3–15 friends, families, teams, or organizations, built around your group, goals, and energy.',
     '[{"label":"Designed for your group","value":"Private workouts, team wellness sessions, celebrations, community groups, and organization programming tailored to your needs."},{"label":"Flexible format","value":"Start at $199 for up to five people, then add $25 for each additional participant, up to 15 total. One-time experiences and recurring monthly groups are offered in designated Echelon event windows."},{"label":"Built around real availability","value":"Share your group size, preferred date, location, and goal. Approved organizers receive a private booking link with only the designated Echelon event slots that are available, so every session is intentional, prepared, and on schedule."}]'::jsonb,
     null, 'live', 20),
    ('12-week-transformation', '12-WEEK TRANSFORMATION', 'Collective Programming',
     'A coached 12-week system for building strength, consistency, and measurable momentum, without guessing what to do next.',
     '[{"label":"Focus","value":"Habit building, progressive overload, nutrition support, and weekly review."},{"label":"Format","value":"A structured 12-week coaching system through the Echelon Member Portal, with weekly review and a shared progression framework."},{"label":"Investment","value":"$399 paid in full, or $149/month."},{"label":"Access","value":"Application required · choose 12-Week Transformation when applying."}]'::jsonb,
     null, 'live', 30),
    ('1-on-1-coaching', '1-ON-1 COACHING', 'Coach: Luther',
     'The highest-touch Echelon experience: fully individualized training, direct accountability, and coaching built around your body, schedule, and goals.',
     '[{"label":"Focus","value":"Individual programming, movement coaching, lifestyle support, and long-term transformation."},{"label":"Format","value":"Private coaching with in-person and hybrid options based on fit."},{"label":"Investment","value":"Coaching is $399/month. Payment begins after your application and consultation are approved."},{"label":"Access","value":"Limited roster · application and consultation required. Approved clients book inside Coach Luther''s released coaching windows."}]'::jsonb,
     'Accepting up to 6 new 1-on-1 clients this month', 'live', 40),
    ('faith-favor-mobility', 'FAITH & FAVOR MOBILITY', 'Coach: TBA',
     'A restorative strength-and-mobility experience designed to improve how you move, recover, and feel between harder training days.',
     '[{"label":"Focus","value":"Mobility, core stability, posture, and active recovery."},{"label":"Format","value":"45-minute small-group session for all experience levels."},{"label":"Launch standard","value":"Opens when coaching coverage and a sustainable recurring schedule are confirmed."}]'::jsonb,
     null, 'in_development', 50),
    ('vl-body-lab', 'VL BODY LAB', 'Coach: TBA',
     'A high-energy athletic training experience blending strength, conditioning, and explosive movement for members who want to build more power.',
     '[{"label":"Focus","value":"Strength, speed, athletic conditioning, and total-body capacity."},{"label":"Format","value":"50-minute group performance session that scales to different experience levels."},{"label":"Launch standard","value":"Opens when coaching coverage and a sustainable recurring schedule are confirmed."}]'::jsonb,
     null, 'in_development', 60),
    ('special-event', '', null, '', '[]'::jsonb, null, 'hidden', 70)
on conflict (program_key) do nothing;
